server:
  port: 8080

spring:
  application:
    name: axel-crm
  datasource:
    url: jdbc:postgresql://localhost:5440/axelcrm
    username: postgres
    password: "123456"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        "[format_sql]": true
    show-sql: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

jwt:
  secret: "c2VuaGFUZXN0ZUFwcGxpY2F0aW9uQm9hdkNvbnN0YW50ZVBhcmEyMDI0"
  expiration: 86400000

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    "[org.springframework.security]": DEBUG
    "[org.springframework.web]": DEBUG
